FROM php:8.2-cli

# Wait-for - Packages
RUN apt update && apt install -y wget ncat

# Wait-for - Used to wait for a specific service (db) within a container to be available
            # before starting the start.sh script
RUN wget -q -O /usr/bin/wait-for https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for && \
    chmod +x /usr/bin/wait-for

# PHP / Laravel - Packages
RUN apt update && apt install -y \
    git \
    unzip \
    libonig-dev \
    libzip-dev \
    zip

# PHP extensions installation
RUN docker-php-ext-install pdo_mysql mbstring zip

# Composer - Composer instalation
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer
RUN php -r "unlink('composer-setup.php');"

# Install Node.js and npm
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get install -y nodejs

# Create user "php"
RUN useradd -u 1000 -ms /bin/bash php

USER php

WORKDIR /home/php/app

COPY ./.bash_aliases        /home/php/
COPY ./start.sh             /usr/local/bin
COPY ./laravel-install.sh   /usr/local/bin

EXPOSE 8081
EXPOSE 5173

CMD [ "/usr/local/bin/start.sh" ]