version: "3.8"

services:
  laravel-app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile.dev
    container_name: laravel-app
    restart: unless-stopped
    command: wait-for database:3306 -t 120 -- /usr/local/bin/start.sh
    ports:
      - "8081:8081"
    volumes:
      - ./app:/home/php/app
    depends_on:
      - database
    networks:
      - network-app

  database:
    image: mysql:8.0
    container_name: database
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=mypasswordroot
      # Set the database user and password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./_dbData:/var/lib/mysql
    networks:
      - network-app

networks:
  network-app:
    driver: bridge